// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtS6-DEUzJYIgp3F0d-v6pZUz4Lv8kFw',
    appId: '1:448832513908:web:10bab73d3b2dd0efa1ae21',
    messagingSenderId: '448832513908',
    projectId: 'academic-atelier-4c514',
    authDomain: 'academic-atelier-4c514.firebaseapp.com',
    storageBucket: 'academic-atelier-4c514.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAdOIlqquL99WlaA52Cpr0COkGapQ8QZg',
    appId: '1:448832513908:android:c8383b82e3b6df33a1ae21',
    messagingSenderId: '448832513908',
    projectId: 'academic-atelier-4c514',
    storageBucket: 'academic-atelier-4c514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYzHYVogw4pyHqxuk3pNU4lgOcThoIDq0',
    appId: '1:448832513908:ios:129f784a083438a9a1ae21',
    messagingSenderId: '448832513908',
    projectId: 'academic-atelier-4c514',
    storageBucket: 'academic-atelier-4c514.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYzHYVogw4pyHqxuk3pNU4lgOcThoIDq0',
    appId: '1:448832513908:ios:129f784a083438a9a1ae21',
    messagingSenderId: '448832513908',
    projectId: 'academic-atelier-4c514',
    storageBucket: 'academic-atelier-4c514.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDtS6-DEUzJYIgp3F0d-v6pZUz4Lv8kFw',
    appId: '1:448832513908:web:6cf8881c3eac1064a1ae21',
    messagingSenderId: '448832513908',
    projectId: 'academic-atelier-4c514',
    authDomain: 'academic-atelier-4c514.firebaseapp.com',
    storageBucket: 'academic-atelier-4c514.firebasestorage.app',
  );
}
